### ISSUE TITLE
Improve Documentation For Builders and Node Operators - V2.0.0

### ISSUE THREAD

**Issue by discoverdefiteam** [terpnetwork/docs#7]
We need docs.terp.network to be a place where users can learn how to interact with Terp Network, and in parallel other interchain related tooling.

## To-Do
- [x] Improve Mission Statement 
- [x] Improve Node Setup Resources
- [x] Improve Cosmwasm Development Examples
- [x] Improve Relayer Operation Guides
- [x] Improve Front End Development Examples
- [x] Clean up Governance details
- [ ] Add A Roadmap
- [x] Add systemd setup for nodes
